### PR TITLE
Fix controls looking blurry on macOS, fixes #2

### LINKED ISSUE #2: Navigation button hovers look awry on macOs
Hello. Noticed the button hovers don't look exactly like they perhaps should:

Screenshot

### PR DESCRIPTION
**Pull request by rollecode**
This seems to fix toolbar button problem on macOS. Not tested on other platforms, feel free to test, confirm and merge.

### CODE REVIEW

**Comment by rollecode** [comment]
Just noticed this fixes it for non-retina, but on laptop screen looks wrong... something about the bitmap.

**Comment by jpminor** [comment]
Yep, it's not a 2x image so there's no fix when using the image included in the package.

**Comment by jpminor** [comment]
What is this a fix for in message view? Nothing to do with the controls right?

**Comment by rollecode** [comment]
Sorry, left open by mistake. This didn't fully fix the controls so I'm closing this...

**Pull request closed without merging**
